Repository nossas/bonde-clients, pull requests merged in 2019-05, with the labels that each got.

#1051 docs: add github issue and pr template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [intangible]

#1068 [public] add fontawesome dependencies
  packages/bonde-public/pages/index.js
Labels: 2.5 bug

#1073 fix(admin): fix required prop on form domain
  packages/bonde-admin/src/mobilizations/components/form-domain.js
Labels: 2.5 bug

#1090 [ public / webpage ] Hotfix / Shared pos action
  lerna.json
  packages/bonde-admin-canary/package.json
  packages/bonde-admin/package.json
  packages/bonde-public/next.config.js
  packages/bonde-public/package.json
  packages/bonde-public/pages/mobilization.connected.js
  packages/bonde-webpage/package.json
  packages/bonde-webpage/src/lib/paths.js
  packages/bonde-webpage/src/lib/plugins/donation/components/tell-a-friend.js
  packages/bonde-webpage/src/lib/plugins/form/components/tell-a-friend.js
Labels: [fixed-date]
